/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiGameTolo;
import gametolo.Tolo;
import gametolo.Bet;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Lenovo
 */
public class BetGUI extends javax.swing.JFrame {

    Tolo tolo = new Tolo();
    int chosenNumber1, chosenNumber2, chosenNumber3, chosenNumber4, chosenNumber5, moneyBet, gainAfterBet;
    /**
     * Creates new form ResultGUI
     */
    public BetGUI() {
        initComponents();
        extraNumberLabel.setVisible(false);
        fifthNumberText.setVisible(false);
        extraNumberDraw.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstNumberText = new javax.swing.JTextField();
        secondNumberText = new javax.swing.JTextField();
        thirdNumberText = new javax.swing.JTextField();
        fourthNumberText = new javax.swing.JTextField();
        submitNumbers = new javax.swing.JButton();
        drawnNumbers = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        betMoneyText = new javax.swing.JTextField();
        gainWithBet = new javax.swing.JLabel();
        displayGain = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        extraNumberLabel = new javax.swing.JLabel();
        fifthNumberText = new javax.swing.JTextField();
        extraNumberDraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(137, 196, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("          Welcome to the Tolo Bet Interface");

        secondNumberText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                secondNumberTextMousePressed(evt);
            }
        });

        submitNumbers.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        submitNumbers.setText("Submit");
        submitNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNumbersActionPerformed(evt);
            }
        });

        drawnNumbers.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        drawnNumbers.setText("Draw Numbers");
        drawnNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawnNumbersActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel7.setText("Bet Amount");

        betMoneyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betMoneyTextActionPerformed(evt);
            }
        });

        gainWithBet.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        gainWithBet.setText("Gain is:");

        displayGain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBox1.setText("SuperBet?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("Enter your Numbers between 1 to 20");

        extraNumberLabel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        extraNumberLabel.setText("Extra Number for Super Bet ");

        fifthNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fifthNumberTextKeyPressed(evt);
            }
        });

        extraNumberDraw.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        extraNumberDraw.setText("Draw Extra Number");
        extraNumberDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraNumberDrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gainWithBet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(displayGain, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawnNumbers)
                            .addComponent(submitNumbers))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(firstNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(secondNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(betMoneyText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(thirdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fourthNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extraNumberLabel)
                            .addComponent(fifthNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraNumberDraw)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(extraNumberLabel))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fifthNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(extraNumberDraw)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betMoneyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(submitNumbers)
                        .addGap(18, 18, 18)
                        .addComponent(drawnNumbers)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gainWithBet)
                    .addComponent(displayGain, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jCheckBox1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNumbersActionPerformed
        // Get four Numbers and Bet Money
        
       try { 
        chosenNumber1 = Integer.parseInt(this.firstNumberText.getText());
        chosenNumber2 = Integer.parseInt(this.secondNumberText.getText());
        chosenNumber3 = Integer.parseInt(this.thirdNumberText.getText());
        chosenNumber4 = Integer.parseInt(this.fourthNumberText.getText());
        moneyBet = Integer.parseInt(this.betMoneyText.getText());
        
        JOptionPane.showMessageDialog(null, "Numbers and your bet amount scucessfully Submitted");
        JOptionPane.showMessageDialog(null, "Click Draw Numbers to check your luck");
    }//GEN-LAST:event_submitNumbersActionPerformed
    catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid Entries: No null Entries Accepted");     
    }
    }
    private void drawnNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawnNumbersActionPerformed
        // TODO add your handling code here:
        //  create Bet and get gain 
        tolo.createBet(chosenNumber1, chosenNumber2, chosenNumber3, chosenNumber4, moneyBet);
        gainAfterBet = tolo.getGain(Tolo.TypeBet.BET);
        String displayBetResult = Integer.toString(gainAfterBet);
        // Display Gain to the label on window
        this.displayGain.setText(displayBetResult);
    }//GEN-LAST:event_drawnNumbersActionPerformed

    private void betMoneyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betMoneyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betMoneyTextActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        extraNumberLabel.setVisible(true);
        fifthNumberText.setVisible(true);
        extraNumberDraw.setVisible(true);
        JOptionPane.showMessageDialog(null, "Enter Extra Number to play Super Bet");
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void extraNumberDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraNumberDrawActionPerformed
        // TODO add your handling code here:
     // Get Extra number  
     try {
     chosenNumber5 = Integer.parseInt(this.fifthNumberText.getText());
     }
     catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid Entry: No null Entries Accepted");     
    }
     tolo.createSuperBet(chosenNumber5, gainAfterBet);
     int gain = tolo.getGain(Tolo.TypeBet.SUPERBET);
     String displaySuperBetResult = Integer.toString(gain);
     
     int luckyNumber = tolo.generateRandomWinningLuckyNumber();
     String displayLuckyNumber = Integer.toString(luckyNumber);
     
     Bet bet = new Bet(moneyBet);
     // ArrayList to get good Numbers
     ArrayList<Integer> toloNumbers = bet.getWinningNumbers();
     
     // ArrayList to Store chossen Numbers
     ArrayList<Integer> playerEnteredNumbers = new ArrayList<Integer>();
     playerEnteredNumbers.add(chosenNumber1);
     playerEnteredNumbers.add(chosenNumber2);
     playerEnteredNumbers.add(chosenNumber3);
     playerEnteredNumbers.add(chosenNumber4);
     playerEnteredNumbers.add(chosenNumber5);
     
     // resultGui is instantiated to connect BetGUI with ResultGUI
      ResultGUI result = new ResultGUI();
      result.setVisible(true);
      result.displayResult(displaySuperBetResult, displayLuckyNumber, toloNumbers, playerEnteredNumbers);
      
    }//GEN-LAST:event_extraNumberDrawActionPerformed

    private void secondNumberTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondNumberTextMousePressed
    JOptionPane.showMessageDialog(null, "Numbers must be entered between 1 to 20");        // TODO add your handling code here:
    }//GEN-LAST:event_secondNumberTextMousePressed

    private void fifthNumberTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fifthNumberTextKeyPressed
    JOptionPane.showMessageDialog(null, "Good you have to Enter a single digit number from 1 to 10");        // TODO add your handling code here:
    }//GEN-LAST:event_fifthNumberTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BetGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betMoneyText;
    private javax.swing.JLabel displayGain;
    private javax.swing.JButton drawnNumbers;
    private javax.swing.JButton extraNumberDraw;
    private javax.swing.JLabel extraNumberLabel;
    private javax.swing.JTextField fifthNumberText;
    private javax.swing.JTextField firstNumberText;
    private javax.swing.JTextField fourthNumberText;
    private javax.swing.JLabel gainWithBet;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField secondNumberText;
    private javax.swing.JButton submitNumbers;
    private javax.swing.JTextField thirdNumberText;
    // End of variables declaration//GEN-END:variables
}
